import schema namespace derivedType =  "http://www.w3.org/XQueryTest/derivedTypes";

16 cast as derivedType:integer,
16 cast as derivedType:double,
16 cast as derivedType:decimal,
16 cast as derivedType:float,
"aaaaaaaaaaaa" cast as derivedType:base64Binary,
"aaaaaaaaaa" cast as derivedType:hexBinary,
"http://news.bbc.co.uk/" cast as derivedType:anyURI,
true() cast as derivedType:boolean,
xs:dateTime("2001-01-01T09:00:00") cast as derivedType:dateTime,
xs:time("10:00:00") cast as derivedType:time,
"valid value 1" cast as derivedType:string,
"value1" cast as derivedType:QName,
"derivedType:value1" cast as derivedType:NOTATION,
"---01" cast as derivedType:gDay,
"--12-25" cast as derivedType:gMonthDay,
"--12" cast as derivedType:gMonth,
"2004" cast as derivedType:gYear,
"2004-02" cast as derivedType:gYearMonth,
"P1D" cast as derivedType:duration,
"1" cast as derivedType:positiveInteger,
"-1" cast as derivedType:nonPositiveInteger,
"1" cast as derivedType:nonNegativeInteger,
"-1" cast as derivedType:negativeInteger,
"1" cast as derivedType:long,
"1" cast as derivedType:short,
"1" cast as derivedType:unsignedByte,
"1" cast as derivedType:byte,
"1" cast as derivedType:unsignedInt,
"1" cast as derivedType:unsignedLong,
"1" cast as derivedType:unsignedShort
