declare default function namespace "http://www.w3.org/2005/xquery-local-functions";

NaN() +
  allowing() +
  ancestor-or-self() +
  ancestor() +
  and() +
  as() +
  ascending() +
  at() +
  base-uri() +
  boundary-space() +
  by() +
  case() +
  cast() +
  castable() +
  catch() +
  child() +
  collation() +
  construction() +
  context() +
  copy-namespaces() +
  count() +
  decimal-format() +
  decimal-separator() +
  declare() +
  default() +
  descendant-or-self() +
  descendant() +
  descending() +
  digit() +
  div() +
  document() +
  else() +
  empty() +
  encoding() +
  end() +
  eq() +
  every() +
  except() +
  external() +
  following-sibling() +
  following() +
  for() +
  ge() +
  greatest() +
  group() +
  grouping-separator() +
  gt() +
  idiv() +
  import() +
  in() +
  infinity() +
  inherit() +
  instance() +
  intersect() +
  is() +
  lax() +
  le() +
  least() +
  let() +
  lt() +
  minus-sign() +
  mod() +
  module() +
  namespace() +
  ne() +
  next() +
  no-inherit() +
  no-preserve() +
  of() +
  only() +
  option() +
  or() +
  order() +
  ordered() +
  ordering() +
  parent() +
  pattern-separator() +
  per-mille() +
  percent() +
  preceding-sibling() +
  preceding() +
  preserve() +
  previous() +
  return() +
  satisfies() +
  schema() +
  self() +
  sliding() +
  some() +
  stable() +
  start() +
  strict() +
  strip() +
  then() +
  to() +
  treat() +
  try() +
  tumbling() +
  unordered() +
  validate() +
  variable() +
  version() +
  when() +
  where() +
  window() +
  xquery() +
  zero-digit() eq
  (107 * (107 + 1)) div 2
