# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js latest
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: 'npm'
    - run: npm ci
    - run: npm run lint-ci

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # The tests depend on TypeScript support
        node-version: [22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run coverage
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.3.6
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run ${{ join(matrix.*, ' - ') }}
          parallel: 'true'

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: 'true'
